Linear Regression using in ml and train the machine

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('clean_insurance_data.csv')
df

      Unnamed: 0  age  gender     bmi  children  smoker  region      charges
0              0   19       1  27.900         0       1       1  16884.92400
1              1   18       2  33.770         1       0       2   1725.55230
2              2   28       2  33.000         3       0       2   4449.46200
3              3   33       2  22.705         0       0       3  21984.47061
4              4   32       2  28.880         0       0       3   3866.85520
...          ...  ...     ...     ...       ...     ...     ...          ...
1332        1333   50       2  30.970         3       0       3  10600.54830
1333        1334   18       1  31.920         0       0       4   2205.98080
1334        1335   18       1  36.850         0       0       2   1629.83350
1335        1336   21       1  25.800         0       0       1   2007.94500
1336        1337   61       1  29.070         0       1       3  29141.36030

[1337 rows x 8 columns]

In [3]:
x=df.drop('charges',axis=1)
x

      Unnamed: 0  age  gender     bmi  children  smoker  region
0              0   19       1  27.900         0       1       1
1              1   18       2  33.770         1       0       2
2              2   28       2  33.000         3       0       2
3              3   33       2  22.705         0       0       3
4              4   32       2  28.880         0       0       3
...          ...  ...     ...     ...       ...     ...     ...
1332        1333   50       2  30.970         3       0       3
1333        1334   18       1  31.920         0       0       4
1334        1335   18       1  36.850         0       0       2
1335        1336   21       1  25.800         0       0       1
1336        1337   61       1  29.070         0       1       3

[1337 rows x 7 columns]

In [4]:
y=df[['charges']]
y

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1332  10600.54830
1333   2205.98080
1334   1629.83350
1335   2007.94500
1336  29141.36030

[1337 rows x 1 columns]

In [5]:
import sklearn as sns 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
#split data in 4 parts 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(1069, 7) (268, 7) (1069, 1) (268, 1)

In [7]:
# create a obect of LinearRegression
lr=LinearRegression()

In [8]:
# train the machine
lr.fit(x_train,y_train)

LinearRegression()

In [9]:
# check score 
lr.score(x_train,y_train)

0.7298794241111717

In [10]:
lr.score(x_test,y_test)

0.8063923204766646

In [11]:
x_test

      Unnamed: 0  age  gender     bmi  children  smoker  region
899          900   49       2  22.515         0       0       4
1063        1064   29       1  25.600         4       0       1
1255        1256   51       1  36.385         3       0       3
298          298   31       2  34.390         3       1       3
237          237   31       2  38.390         2       0       2
...          ...  ...     ...     ...       ...     ...     ...
534          534   64       2  40.480         0       0       2
542          542   63       1  36.300         0       0       2
759          760   22       1  34.580         2       0       4
1283        1284   61       2  36.300         1       1       1
1284        1285   47       1  24.320         0       0       4

[268 rows x 7 columns]

In [12]:
pred=lr.predict(x_test)#predict the data 
pred

array([[ 8176.713261  ],
       [ 5726.50272857],
       [14604.13072017],
       [31579.12528333],
       [ 8991.50160529],
       [13296.26919086],
       [30077.85113557],
       [ 1147.21612329],
       [10753.45297708],
       [11391.78531611],
       [10375.31675116],
       [33031.46186635],
       [31130.29749638],
       [17271.31294167],
       [10620.47275184],
       [ 9309.80950711],
       [ 3782.74694151],
       [31682.51199667],
       [ 3100.93970108],
       [ 5240.21407618],
       [ 3739.05147646],
       [30211.16382742],
       [15074.07080704],
       [30210.85032501],
       [31134.67053179],
       [ 5270.57764881],
       [35911.01737288],
       [36564.64335959],
       [11184.75602295],
       [13961.12101457],
       [ 6301.8730285 ],
       [13129.041441  ],
       [  804.193988  ],
       [11791.14390464],
       [39743.63139988],
       [12224.01488895],
       [ 4308.65929188],
       [ 4173.05404774],
       [31197.8527679 ],
       [ 9172.73467125],
       [ 6638.09336663],
       [30110.95663081],
       [34832.0796559 ],
       [12385.55232354],
       [ 7415.38769195],
       [ 3405.97724054],
       [ 6038.97091737],
       [ 9043.95223935],
       [ 4080.01158791],
       [ 9439.32467898],
       [ 6676.77414535],
       [12051.94878327],
       [31326.88269682],
       [ 3655.51537142],
       [10956.48641439],
       [ 9801.44949643],
       [10883.89345702],
       [ 2639.47194438],
       [31516.78391733],
       [ 9407.28134329],
       [15640.91778284],
       [ 8505.05426128],
       [12595.37052369],
       [ 1731.47633327],
       [17009.01268143],
       [10699.98410547],
       [10187.53063101],
       [30822.46431925],
       [24422.8449676 ],
       [16407.89608255],
       [ 7562.24832452],
       [ 2758.80077337],
       [ 7284.35870589],
       [ -141.33425294],
       [11765.54992801],
       [-1057.95679403],
       [16834.57128705],
       [ 8705.49777277],
       [ 7601.93207447],
       [12520.58109897],
       [ 5878.57314996],
       [18608.81941962],
       [15394.53377225],
       [11174.62515162],
       [36191.72990698],
       [13363.8906181 ],
       [ 4056.21947617],
       [ 2409.10238428],
       [ 6496.40536344],
       [ 4202.54243805],
       [15174.73240939],
       [28454.20708337],
       [ 5576.40344628],
       [ 3147.42215154],
       [ 1757.94383888],
       [35787.53485362],
       [14554.60726375],
       [ 8993.14072317],
       [ 4568.97796922],
       [ 8656.99481847],
       [13687.82866991],
       [14968.69162281],
       [32162.01423733],
       [14393.90418145],
       [32681.44767866],
       [  164.3754857 ],
       [30718.28939791],
       [26497.10083553],
       [14026.5895555 ],
       [ 5964.4272977 ],
       [ 8131.80713177],
       [11609.17619533],
       [ 8307.94735227],
       [10226.87035631],
       [ 6044.26976453],
       [ 5395.7363494 ],
       [ 2251.15050907],
       [ 3490.59189737],
       [ 7082.678775  ],
       [ 9355.93445375],
       [36358.30102068],
       [ 7963.30755852],
       [11597.88128229],
       [ 9453.52649342],
       [ 9206.9254143 ],
       [ 9719.62370395],
       [ 4384.40766888],
       [12334.76150115],
       [29835.06969407],
       [38568.58829236],
       [36290.55251288],
       [11896.42381841],
       [ 2456.364148  ],
       [11721.54673456],
       [10152.50051066],
       [ 5510.43477311],
       [34874.11013478],
       [29702.26233018],
       [25545.98067317],
       [ 5161.36765015],
       [ 6380.48251422],
       [ 5744.30766934],
       [36625.36471641],
       [10906.91237516],
       [ 5757.57461865],
       [ 8014.03008343],
       [10382.00823172],
       [ 8407.8108494 ],
       [35183.76584531],
       [14417.98560815],
       [ 9612.80318544],
       [ 6969.04895915],
       [ 6797.02319375],
       [16624.49850209],
       [ 7411.69487564],
       [26572.48102413],
       [36512.12189227],
       [16349.88129894],
       [10147.54369819],
       [10996.9458158 ],
       [12569.4437601 ],
       [ 4184.39495828],
       [12889.77798132],
       [13626.88987497],
       [35468.00258635],
       [32976.00600943],
       [13130.63831336],
       [25253.8064477 ],
       [ 2463.58168972],
       [ 1957.81037632],
       [ 5216.50399035],
       [ 5163.23555179],
       [ 5281.10741438],
       [10062.18815095],
       [10085.93114197],
       [26122.95080429],
       [ 2119.68359121],
       [11076.93992836],
       [ 6931.33961438],
       [12010.96856282],
       [15036.56799059],
       [ 4913.40336623],
       [11024.46752186],
       [10024.78148285],
       [33021.79215279],
       [11099.3272004 ],
       [ 7109.46918741],
       [ 5837.72338972],
       [  555.3368385 ],
       [31066.25554715],
       [ 8044.14241194],
       [32970.73826663],
       [12368.22494957],
       [ 6371.04508135],
       [ 1400.69424715],
       [ 2324.94799464],
       [32539.6443449 ],
       [ 4718.38614794],
       [13289.42222742],
       [17283.34062271],
       [26205.6069547 ],
       [25739.75662036],
       [ 6903.10311601],
       [12279.32852755],
       [28389.13748027],
       [ 7590.09393246],
       [10176.2591039 ],
       [10070.71339506],
       [ 3297.52140855],
       [34649.61300139],
       [31585.25953928],
       [ 9946.92722163],
       [ 6019.26007703],
       [ 7953.84479945],
       [10841.25594814],
       [ 4793.4709478 ],
       [ 4885.60966976],
       [11729.24448307],
       [ 9347.23393959],
       [ 3078.6261894 ],
       [ 4057.37549085],
       [37558.76051814],
       [37262.43453161],
       [13037.45944744],
       [11246.49598441],
       [37859.38503565],
       [34139.00594419],
       [ 6865.26929824],
       [26839.46153276],
       [ 4067.5410771 ],
       [16209.34828303],
       [29141.98078387],
       [ 5581.23125354],
       [ 9439.32053909],
       [ 8881.61819775],
       [ 9366.41905393],
       [ 9771.73907659],
       [ 4722.03826675],
       [ 5940.11308184],
       [ 4650.17751303],
       [ 6164.47205033],
       [ 5010.31387042],
       [ 5719.6008301 ],
       [ 8561.7162791 ],
       [ 1126.31558924],
       [ 8524.10012553],
       [ 3716.34809115],
       [10563.36641158],
       [ 2444.58118279],
       [10449.23856436],
       [ 3720.50852385],
       [11810.45185916],
       [12131.9638438 ],
       [14168.13308535],
       [37200.64721281],
       [23250.08424177],
       [ 9973.5340585 ],
       [ 7803.33226255],
       [ 8992.87558191],
       [12501.68189288],
       [29564.3331373 ],
       [37869.60479307],
       [14959.52425669],
       [16922.16076395],
       [15462.43781555],
       [ 6327.09155794],
       [38493.76338667],
       [ 8485.58290325]])

In [13]:
y_test

          charges
899    8688.85885
1063   5708.86700
1255  11436.73815
298   38746.35510
237    4463.20510
...           ...
534   13831.11520
542   13887.20400
759    3925.75820
1283  47403.88000
1284   8534.67180

[268 rows x 1 columns]