### ML_TreeRegression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('clean_laptopPrice.csv')
df

,Unnamed: 0,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price
0,0,10,1,3,10,4,1,0,1024,1,64,0,1,0,0,0,34649
1,1,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0,38999
2,2,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0,39999
3,3,10,1,5,10,8,1,512,0,1,32,2,1,0,0,0,69990
4,4,10,1,1,0,4,1,0,512,1,64,0,1,0,0,0,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,818,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0,135990
782,819,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0,144990
783,820,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0,149990
784,821,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0,142990
785,822,20,2,6,10,8,1,512,0,2,64,0,2,0,0,0,57490

In [3]:
x=df.drop('Price',axis=1)
x

,Unnamed: 0,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice
0,0,10,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
1,1,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
2,2,20,1,3,10,4,1,0,1024,1,64,0,1,0,0,0
3,3,10,1,5,10,8,1,512,0,1,32,2,1,0,0,0
4,4,10,1,1,0,4,1,0,512,1,64,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,818,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0
782,819,10,2,10,0,4,1,1024,0,1,64,0,1,1,0,0
783,820,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0
784,821,10,2,10,0,4,1,1024,0,1,64,4,1,1,0,0
785,822,20,2,6,10,8,1,512,0,2,64,0,2,0,0,0

In [4]:
y=df[['Price']]
y

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
781  135990
782  144990
783  149990
784  142990
785   57490

[786 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
from sklearn.tree import DecisionTreeRegressor
dr=DecisionTreeRegressor(criterion='gini')# data kam ke liye gini use karege
dr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [7]:
dr.fit(x_train,y_train)

InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'friedman_mse', 'squared_error', 'poisson'}. Got 'gini' instead.

In [ ]:
pred=dr.predict(x_test)

In [ ]:
pred=dr.predict(x_test)
pred

In [ ]:
pred[0:20]